version: '3'

services:
  reddit-spy:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./config/.env:/app/config/.env
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /mnt/user/appdata/reddit-spy:/data/db
    restart: unless-stopped
